name: Target Dispatch Action

on:
  repository_dispatch:
    types: [MyCustomEventName]
  
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:    
      - name: Print client payload
        run: |
          echo 'ParamA' is ${{ github.event.client_payload.paramA }}
          echo 'ParamBoolean' is ${{ github.event.client_payload.paramBoo }}
          
      - name: Set Output
        run: |
          echo "ParamA=${{ github.event.client_payload.paramA }}" >> $GITHUB_OUTPUT
          echo "ParamBoolean=${{ github.event.client_payload.paramBoo }}" >> $GITHUB_OUTPUT
               
