name: Target Dispatch Action

on:
  repository_dispatch:
    types: [MyCustomEventName]
  
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:    
      - name: Print client payload
        run: |
          echo 'ParamA' is ${{ github.event.client_payload.paramA }}
          echo 'ParamBoolean' is ${{ github.event.client_payload.paramBoo }}


      - name: Set Annotations
        run: |
          echo "::notice::ParamA : ${{ github.event.client_payload.paramA }}
          echo "::notice::ParamBoolean : ${{ github.event.client_payload.paramBoo }}"

